### ISSUE TITLE
How to modify sass variables?

### ISSUE THREAD

**Issue by yandixuan** [yujinpan/el-css-var#1]
https://element-plus.org/zh-CN/guide/theming.html#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%AE%83%EF%BC%9F

**Comment by yujinpan** [comment]
It was add at v1.0.1-beta.1

https://yujinpan.github.io/el-css-var/#scss-variables

**Comment by yandixuan** [comment]
`$font-path: '~el-css-var/dist/fonts'` also important

**Comment by yujinpan** [comment]
👍, the documentation has been updated.

**Comment by yandixuan** [comment]
but css variablse should be written from scss variabls just like element-plus?
