### ISSUE TITLE
el-col width error

### ISSUE THREAD

**Issue by yandixuan** [yujinpan/el-css-var#2]
![image](https://github.com/yujinpan/el-css-var/assets/23276822/9fbb4e92-f773-417a-9076-d5830593e181)
![image](https://github.com/yujinpan/el-css-var/assets/23276822/8a95100f-2b7d-4d45-9ba3-350ee2b23140)

actual：6/24*100%=25% 

https://github.com/yujinpan/el-css-var/blob/7d0720908391c9dffdf6284c4928b8c05fcc32fd/src/theme-chalk/v2-generate.js#L181

**Comment by yujinpan** [comment]
👍

Fixed in v1.0.1-beta.2!
